### ISSUE TITLE
Mobs and Items

### ISSUE THREAD

**Issue by amh231** [CS3398-Bronze-Statues/CS3398-Bronze-S2017#42]
As developers, we need mobs to interact with the combat system and items in our game.

**Comment by cc1778** [comment]
We are dropping this work from sprint 1 because we underestimated our python learning tasks which took much more time than anticipated.  As a result, we spent a large amount of time learning python, and did not have time to complete all of the framework discussion.

Although this was marked in progress, we consider the work done on it negligible and will revisit it in the future.

**Comment by cbFowler** [comment]
Moving issue to closed as it is being replaced by an epic that includes issues dealing with these topics.
