### ISSUE TITLE
Create UML of Game Structure 

### ISSUE THREAD

**Issue by amh231** [CS3398-Bronze-Statues/CS3398-Bronze-S2017#44]

**Comment by cc1778** [comment]
We are dropping this work from sprint 1 because we underestimated our python learning tasks which took much more time than anticipated.  As a result, we spent a large amount of time learning python, and did not have time to complete all of the framework discussion.

Although this was marked in progress, we consider the work done on it negligible and will revisit it in the future.  We are unable to get a full UML created without having all of the framework discussion complete.

**Comment by cc1778** [comment]
Moving this to closed because it is no longer something to be done for this project.
